### ISSUE TITLE
Cannot find module 'nightwatch/lib/testsuite/reporter'

### ISSUE THREAD

**Issue by williamthewill** [karriereat/vue-cli-plugin-e2e-nightwatch-cucumber#5]
Hi guy, 
I run the command to install the plugin, `vue  add e2e-nightwatch-cucumber`, to end I received this error after run `npm run test:e2e`

```js
Unhandled rejection Error: Cannot find module 'nightwatch/lib/testsuite/reporter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/.../view/node_modules/nightwatch-api/lib/client.js:16:40)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/.../view/node_modules/nightwatch-api/lib/index.js:27:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)```

nightwatch.conf file
```js
const config = require('vue-cli-plugin-e2e-nightwatch-cucumber/nightwatch.conf');
module.exports = { ...config };
```
package.json file
```js
"scripts": {
    "serve": "npm update && vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "dev-docker": "vue-cli-service serve --port 3001",
    "postinstall": "npm prune",
    "test:ui": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "dgt-vitra": "^1.0.14",
    "dgt-vue-components": "^1.0.28",
    "nightwatch": "^0.9.21",
    "vue": "^2.5.13",
    "vue-router": "^2.7.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/runtime": "^7.1.5",
    "@babel/runtime-corejs2": "^7.1.5",
    "@vue/cli-plugin-babel": "^3.0.4",
    "@vue/cli-plugin-e2e-nightwatch": "^3.2.0",
    "@vue/cli-plugin-eslint": "^3.0.4",
    "@vue/cli-plugin-unit-mocha": "^3.2.0",
    "@vue/cli-service": "^3.0.4",
    "@vue/test-utils": "^1.0.0-beta.25",
    "babel-core": "^7.0.0-bridge.0",
    "babel-preset-env": "^1.7.0",
    "css-loader": "^0.25.0",
    "eslint": "^5.7.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-html": "^4.0.6",
    "node-sass": "^4.10.0",
    "sass-loader": "^6.0.6",
    "vue-cli-plugin-e2e-nightwatch-cucumber": "^1.0.0",
    "vue-template-compiler": "^2.5.17"
  }```

**Comment by Lorti** [comment]
Hi William, the plugin requires Nightwatch 1.x. You have Nightwatch 0.9.x listed as one of your dependencies.

**Comment by williamthewill** [comment]
Thanks man

**Comment by Lorti** [comment]
You don't have to explicitly set a Nightwatch version, the plugin requires it, so you can delete it from your package.json. Let me know if I can help or something's not working.
