### ISSUE TITLE
timeout ever after first step

### ISSUE THREAD

**Issue by williamthewill** [karriereat/vue-cli-plugin-e2e-nightwatch-cucumber#6]
Man, the first step fail with timeout every time. I do not know what I did wrong.

Error log
```js
Feature: Home page
  Scenario: Check expected elements on home page
    Given I open the home page
✔ Element <#app> was visible after 149 milliseconds.
    ✖ failed
      Error: function timed out, ensure the promise resolves within 10000 milliseconds
          at Timeout._onTimeout (/.../node_modules/cucumber/lib/user_code_runner.js:93:22)
          at ontimeout (timers.js:436:11)
          at tryOnTimeout (timers.js:300:5)
          at listOnTimeout (timers.js:263:5)
          at Timer.processTimers (timers.js:223:10)
    Then I see the element ".hello"
    - skipped
    And the element "h1" contains text "Welcome to Your Vue.js App"
    - skipped
    And I count 1 element "img"
    - skipped
afterAll

Failures:
1) Scenario: Check expected elements on home page # tests/features/home_page.feature:3
   ✖ Given I open the home page # tests/step-definitions/steps.js:6
       Error: function timed out, ensure the promise resolves within 10000 milliseconds
           at Timeout._onTimeout (/.../node_modules/cucumber/lib/user_code_runner.js:93:22)
           at ontimeout (timers.js:436:11)
           at tryOnTimeout (timers.js:300:5)
           at listOnTimeout (timers.js:263:5)
           at Timer.processTimers (timers.js:223:10)
   - Then I see the element ".hello" # tests/step-definitions/steps.js:12
   - And the element "h1" contains text "Welcome to Your Vue.js App" # tests/step-definitions/steps.js:16
   - And I count 1 element "img" # tests/step-definitions/steps.js:20

1 scenario (1 failed)
4 steps (1 failed, 3 skipped)
0m10.004s
```
steps.js
```js
const { client } = require('nightwatch-api');
const { Given, When, Then, setDefaultTimeout } = require('cucumber');

Given('I open the home page', function() {
    return client
        .url(process.env.VUE_DEV_SERVER_URL)
        .waitForElementVisible('#app', 5000);
});

Then('I see the element {string}', function(element) {
    return client.assert.elementPresent(element);
});

Then('the element {string} contains text {string}', function(element, text) {
    return client.assert.containsText(element, text);
});

Then('I count {int} element {string}', function(count, element) {
    return client.assert.elementCount(element, count);
});
```
home_page.feature
```js
Feature: Home page
  Scenario: Check expected elements on home page
    Given I open the home page
    Then I see the element ".hello"
    And the element "h1" contains text "Welcome to Your Vue.js App"
    And I count 1 element "img"
```
nightwatch.conf.js
```js
const merge = require('lodash.merge');
const config = require('vue-cli-plugin-e2e-nightwatch-cucumber/nightwatch.conf');

// https://lodash.com/docs/4.17.10#merge
module.exports = merge(config, {
    test_settings: {
        default: {
            desiredCapabilities: {
                chromeOptions: {
                    // Override `['headless', 'disable-gpu']` to show Chrome's UI for debugging
                    args: ['disable-gpu']
                }
            }
        }
    }
});
```

**Comment by williamthewill** [comment]
webDriver never closes

**Comment by Lorti** [comment]
I'll take a look on Monday or Tuesday. Until then, if you find a solution, please feel free to open up a pull request.

**Comment by Lorti** [comment]
I haven't been able to find the exact problem, but there seem to be other who have a similar problem with Nightwatch API (which is the package I'm using for this plugin): https://github.com/mucsi96/nightwatch-api/issues/44

In your case, however, I think the problem is `VUE_DEV_SERVER_URL`. That variable might not be set, as tests are run in production mode per default. What's in your `process.env.VUE_DEV_SERVER_URL`?

**Comment by Lorti** [comment]
I have now exposed the dev server URL as VUE_DEV_SERVER_URL. Your tests shouldn't timeout now.

https://www.npmjs.com/package/vue-cli-plugin-e2e-nightwatch-cucumber/v/1.0.1
https://github.com/karriereat/vue-cli-plugin-e2e-nightwatch-cucumber/blob/master/index.js#L18

**Comment by williamthewill** [comment]
thanks man, I will test again in the end day. I will send you a message with the result.
